HH-115085 add russian error on duplicate example of response
hhru/api pull request #444
Opened 2020-09-07 09:13 UTC by Diacrome

https://jira.hh.ru/browse/HH-115085

2020-09-07 14:05 UTC, colorbash reviewed
не увидел инфы что мы выдаем только 10 из дубликатов

2020-09-07 14:05 UTC, colorbash commented on docs/errors.md
> +403 | vacancies | duplicate | | аналогичная вакансия уже опубликована. В [ответе](#vacancies-duplicate-response) передается количество дубликатов и ограниченное количество примеров: их идентификаторы
не очень нравится слово пример, можно просто тут указать 
В [ответе](#vacancies-duplicate-response) передается информация по дубликатам вакансии
а раскрыть ее полностью уже внизу, что именно передается

2020-09-07 14:05 UTC, colorbash commented on docs/errors.md
> +        "count_duplicates": 2,
просто count

2020-09-07 14:05 UTC, colorbash commented on docs/errors.md
> +        "examples_of_duplicates": [
или vacancy_duplicates

2020-09-07 15:09 UTC, iriss22 commented on docs/errors.md
> +        "examples_of_duplicates": [
я бы items назвала. У нас везде в ответах так

2020-09-07 15:09 UTC, iriss22 commented on docs/errors.md
> +        "count_duplicates": 2,
этот count ведь не равен количеству, которое мы выводим?

2020-09-07 15:09 UTC, iriss22 commented
думаю, что число 10 не нужно указывать в доке

2020-09-07 18:45 UTC, Diacrome commented on docs/errors.md
> +        "count_duplicates": 2,
Все верно, не равен. Может быть больше лимита.

2020-09-08 06:19 UTC, Diacrome commented on docs/errors.md
> +        "examples_of_duplicates": [
Унификация это хорошо

2020-09-08 06:20 UTC, Diacrome commented
Специально не написал лимит, может нам завтра захочется 11

2020-09-08 06:21 UTC, Diacrome commented on docs/errors.md
> +        ]
да, понадеялся на копию. исправлю

2020-09-08 07:20 UTC, colorbash commented on docs/errors.md
> +
тут лучше таблицей, посмотри как мы описываем поля жсона https://github.com/hhru/api/pull/444/commits/27745aefe6df525c6b1bb5282f83d7606c0a046d#diff-16ccaa8cf4bef8b523bd972c580b07d8L318

2020-09-08 07:26 UTC, Diacrome commented on docs/errors.md
> +
Ок, я посмотрел в доке. Было так и так.
Да, таблица лучше выглядит

2020-09-08 07:44 UTC, colorbash approved these changes

2020-09-08 10:58 UTC, iriss22 requested changes
пара замечаний и ок

2020-09-08 10:58 UTC, iriss22 commented on docs/errors.md
> +            "count": 2,
может используем https://github.com/hhru/api/blob/master/docs/general.md#%D0%BF%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0%D1%86%D0%B8%D1%8F ?
мне кажется, что в таком исполнении поле count может сбивать

2020-09-08 10:58 UTC, iriss22 commented on docs/errors.md
> +            "type": "duplicate",
судя по https://github.com/hhru/api/blob/master/docs/errors.md#%D0%BF%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F-%D0%B8-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B9
было бы логично значения type и value поменять местами

2020-09-09 06:21 UTC, Diacrome commented on docs/errors.md
> +            "type": "duplicate",
действительно.
странно что сейчас так

2020-09-09 06:22 UTC, Diacrome commented on docs/errors.md
> +            "count": 2,
унификация это хорошо

2020-09-09 11:57 UTC, iriss22 approved these changes

2020-09-18 09:28 UTC, iriss22 approved these changes

2020-09-21 12:11 UTC, merged