HH-124512 add employer badge field to employer and vacancy
hhru/api pull request #474
Opened 2021-02-18 12:55 UTC by SuhoyVasya

2021-02-18 14:59 UTC, iriss22 approved these changes
Надо не забыть добавить английскую доку

2021-02-20 06:32 UTC, iriss22 requested changes

2021-02-20 06:32 UTC, iriss22 commented on docs_eng/employers.md
> + Имя            | Тип    | Описание
на английском

2021-02-20 06:32 UTC, iriss22 commented on docs_eng/vacancies.md
> +                "description": "2-е место в Рейтинге работодателей России (небольшие компании)",
тут лучше тоже на английском
или у нас на русском выведется?

2021-02-20 06:33 UTC, SuhoyVasya commented on docs_eng/vacancies.md
> +                "description": "2-е место в Рейтинге работодателей России (небольшие компании)",
тут пока есть только русский, вроде переводить не собирались

2021-02-20 06:35 UTC, SuhoyVasya commented on docs_eng/employers.md
> + Имя            | Тип    | Описание
оооооо моя копипаста
поправил

2021-02-20 06:39 UTC, iriss22 approved these changes

2021-02-25 11:50 UTC, closed without merging