Добавили информацию о доступных улучшениях для вакансии.
hhru/api pull request #481
Opened 2021-05-06 11:00 UTC by Afftobus

задача https://jira.hh.ru/browse/HH-128865
перенос отсюда
https://github.com/hhru/hhapi/blob/master/docs/private/ru/vacancy_upgrades.md

2021-05-06 11:00 UTC, colorbash commented
нужна ссылка с оглавления

2021-05-06 13:57 UTC, colorbash commented on docs/employer_vacancy_upgrades.md
> +without_action | boolean | null в случае, если присутствуют элементы в actions или объект с писанием причины, по которой не возможно улучшение вакансии до данного типа
или null в типе

2021-05-06 13:58 UTC, colorbash commented on docs/employer_vacancy_upgrades.md
> +* `404 Not Found` — если вакансия не найдена или у пользователя нет прав на просмотр данной вакансии
в какиех случаях у пользователя нет прав ?

2021-05-06 13:59 UTC, colorbash approved these changes

2021-05-06 14:48 UTC, Afftobus commented on docs/employer_vacancy_upgrades.md
> +* `404 Not Found` — если вакансия не найдена или у пользователя нет прав на просмотр данной вакансии
когда он запрашивает чужую вакансию

2021-05-06 15:02 UTC, stalker1152 commented on docs/employer_vacancy_upgrades.md
> +* `404 Not Found` — если вакансия не найдена или у пользователя нет прав на просмотр данной вакансии
- Вакансия принадлежит другому менеджеру
- У данного менеджера нет права на работу с данной вакансией (право дается под ГКЛ например)

2021-05-06 15:06 UTC, iriss22 requested changes

2021-05-06 15:06 UTC, iriss22 commented on docs/employer_vacancy_upgrades.md
> +cart_id | integer | идентификатор заказа, ожидающего активации. Присутствует для `type=activate`
тут или null видимо

2021-05-06 15:19 UTC, Afftobus commented on docs/employer_vacancy_upgrades.md
> +cart_id | integer | идентификатор заказа, ожидающего активации. Присутствует для `type=activate`
этих самых неактивированных заказов может быть несколько и непонятно, как их различить чисто по урлу. А если есть cart_id, то можно по таковому получить какую-то инфу и показать

2021-05-06 15:20 UTC, iriss22 approved these changes

2021-05-07 06:20 UTC, colorbash commented
Как будто стоит написать об этом в твиттере

2021-05-07 06:20 UTC, closed without merging