Добавили информацию о черновиках вакансий.
hhru/api pull request #483
Opened 2021-05-19 10:15 UTC by Afftobus

Задача https://jira.hh.ru/browse/HH-129448
Информация по черновикам.

2021-05-19 13:17 UTC, colorbash commented on docs/vacancy_drafts.md
> +      "id": 1110032,
ид стараемся строкой отдавать

2021-05-19 13:17 UTC, colorbash commented on docs/vacancy_drafts.md
> +      "id": 1110032,
и можно наверное draft_id тк находится в items, не сразу можно понять к чему это

2021-05-19 13:17 UTC, colorbash commented on docs/vacancy_drafts.md
> +insufficient_quotas | array или null | Массив объектов с информацией о том, каких квот не хватает на счету для публикации вакансии из данного черновика.
может какие квоты превышены?

2021-05-19 13:17 UTC, colorbash commented on docs/vacancy_drafts.md
> +name | string | Название
вакансии

2021-05-19 13:17 UTC, colorbash commented on docs/vacancy_drafts.md
> +В случае успешного выполнения запроса, будет возвращён статус `204 OK`.
ошибки? 403, 404?

2021-05-19 13:17 UTC, colorbash commented on docs/vacancy_drafts.md
> +required_publications | array или null | Массив объектов с информацией о необходимых публикациях на счету
можно запутаться с insufficient_publications, может required_publications переименовть в price или что-то подобное?

2021-05-19 13:17 UTC, colorbash commented on docs/vacancy_drafts.md
> +publication_ready | boolean  | Готовность черновика к публикации
если не готов будет описание почему?

2021-05-19 13:29 UTC, colorbash commented on docs/vacancy_autopublication.md
> +воспользуйтесь [ресурсом с информаций по черновикам](vacancy_drafts.md).
не рабочая ссылка

2021-05-19 13:29 UTC, colorbash commented on docs/vacancy_drafts.md
> +        "cart_id": 5967030
строкой

2021-05-19 13:29 UTC, colorbash commented on docs/vacancy_autopublication.md
> +## Отмена автоматической публикации вакансии из черновика
может описать что есть Автопубликация, как она работает и когда публикует из черновика?

2021-05-19 14:04 UTC, Afftobus commented on docs/vacancy_drafts.md
> +required_publications | array или null | Массив объектов с информацией о необходимых публикациях на счету
ну тут типа 
"сколько вообще надо " и 
"сколько не хватает"

вроде кажется адекватно

2021-05-19 14:05 UTC, Afftobus commented on docs/vacancy_drafts.md
> +publication_ready | boolean  | Готовность черновика к публикации
не планировал. 
ответ должен быть с проценте заполнения и ошибках валидации

2021-05-19 14:44 UTC, adanilkina requested changes

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_autopublication.md
> +###Запрос
пробел забыл
![image](https://user-images.githubusercontent.com/36441126/118827002-a4a04600-b8c4-11eb-88de-e6ac18c2a00c.png)

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_autopublication.md
> +* `404 Not Found` — если вакансия не найдена или у пользователя нет прав на просмотр данной вакансии
наверное ток не вакансии, а черновика

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_autorenewal.md
> +* `404 Not Found` — если черновик не найден или у пользователя нет прав на просмотр данного черновика.
а здесь наоборот вакансии

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_drafts.md
> +      ],
а какое отношение к черновикам имеют регионы?
из описания поля непонятно

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_drafts.md
> +      ],
у нас есть https://github.com/hhru/api/blob/master/docs/employer_vacancies.md#available_types

там есть варианты публикаций(publications), в котором доступные для публикации регионы представлены ссылкой publications[].areas_url - нельзя его использовать?

если нельзя, то надо подумать, как это будет выглядеть, если будет много регионов?

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_drafts.md
> +          "count": 2,
при каких обстоятельствах count будет 2?
из описания: 
`insufficient_publications | array или null | Массив объектов с информацией о том, каких публикаций не хватает на счету для публикации ВАКАНСИИ из данного черновика.` - кажется, что если на счету нет публикаций нужного типа, то всегда будет не хватать 1, тоже самое с квотами

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_drafts.md
> +completed_fields_percentage | number | Процент заполнения черновика
а почему в примере null? если мб null, то когда?

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_drafts.md
> +      "validation_errors": null
пример бы... а то не оч понятно, как выглядит

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_drafts.md
> +insufficient_quotas | array или null | Массив объектов с информацией о том, какие квоты превышены.
а можно сделать `объектов` ссылкой везде на объекты, а то так не оч понятно, что за объект вернется

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_drafts.md
> +cart_id | number | Идентификатор заказа
а как состояние автопубликации связано со счетом и покупкой?
надо как-то переназвать или пояснить.

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_drafts.md
> +* `403 Forbidden` — текущий пользователь не является работодателем
а если у менеденжера не будет черновиков, какой ответ вернется?

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_drafts.md
> +insufficient_publications | array или null | Массив объектов с информацией о том, каких публикаций не хватает на счету для публикации вакансии из данного черновика.
мб путсой массив, как в примере?
или в примере надо исправить на null, тоже самое про insufficient_quotas, required_publications

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_drafts.md
> +      "validation_errors": null
`+` добавить в описание тип обектов

2021-05-19 14:44 UTC, adanilkina commented on docs/vacancy_drafts.md
> +
сколько у менеджеров обычно черновиков, per_page не нужен?

2021-05-19 14:53 UTC, Afftobus commented on docs/vacancy_drafts.md
> +          "count": 2,
ну у нас же из одного черновика может выйти несколько вакансий по количеству регионов. Захотел чувак в 10 регионах опубликовать, а у него 8 публикаций на счету.

2021-05-19 14:56 UTC, Afftobus commented on docs/vacancy_drafts.md
> +completed_fields_percentage | number | Процент заполнения черновика
null возвращается из автопубликаций. Хотя ты права, по сути там сейчас (на бэке) null когда черновик уже прошел все валидации и в таком случае можно смело писать 100

2021-05-19 14:57 UTC, Afftobus commented on docs/vacancy_drafts.md
> +* `403 Forbidden` — текущий пользователь не является работодателем
пустой items []

2021-05-20 07:38 UTC, mvxio commented on docs/vacancy_autopublication.md
> +```DELETE /vacancies/auto_publication/{draft_id}```
Какая-то несогласованность с get-методом.
Может быть так?
```suggestion
```DELETE /vacancies/drafts/{draft_id}/auto_publication```
```

2021-05-20 07:38 UTC, colorbash commented on docs/vacancy_autorenewal.md
> +###Запрос
пробел

2021-05-20 07:45 UTC, mvxio commented on docs/vacancy_autopublication.md
> +```DELETE /vacancies/auto_publication/{draft_id}```
Мне не очень нравится, что тут используется path-параметр.
Готовый урл будет выглядеть так:
_/vacancies/auto_publication/1455_, как будто 1455 — ид автопубликации, а не драфта.

Возможно стоит сделать query-параметр, тогда будет яснее:
_/vacancies/auto_publication?draft_id=1455_

2021-05-20 07:49 UTC, mvxio commented on docs/vacancy_autorenewal.md
> +```DELETE /vacancies/auto_renewal/{vacancy_id}```
Тут тоже стоит подумать над расположением ид вакансии.
Потому что прям получается _/vacancies/auto_renewal/1234_.

Хотя, возможно, более наглядно было бы так:
_/auto_renewal/vacancies/1234_
Или так:
_/vacancies/auto_renewal?vacancy_id=1234_

В плюсы query-параметров можно отнести возможность батчевания, вдруг вы захотите много вакансий автообновлять

2021-05-20 07:50 UTC, mvxio commented on docs/vacancy_drafts.md
> +```DELETE /vacancies/drafts/{draft_id}```
👍

2021-05-20 13:04 UTC, mvxio approved these changes

2021-05-20 13:23 UTC, colorbash commented on docs/vacancy_autopublication.md
> +```DELETE /vacancies/auto_publication/{draft_id}```
вообще кажется вкусовщина, массив ид можно и в пути передать, а вот ничего не передать уже не получится в отличии от квери. а не хочется чтобы казалось чтобы ничего нельзя передать.

2021-05-20 13:26 UTC, colorbash approved these changes

2021-05-20 14:18 UTC, adanilkina commented on docs/vacancy_drafts.md
> +      "validation_errors": null
я не оч поняла, а ты забыл про поле или что-то недопушил?

2021-05-20 14:31 UTC, adanilkina commented on docs/vacancy_drafts.md
> +cart_id | string | Идентификатор заказа
а пользователь где-то видит cart_id?

2021-05-20 14:32 UTC, Afftobus commented on docs/vacancy_drafts.md
> +cart_id | string | Идентификатор заказа
он где-то сможет увидеть инфу по счету отдельным запросов. Ну или сформировать ссылку прямо на корзину.

2021-05-20 14:33 UTC, adanilkina approved these changes

2021-05-20 14:33 UTC, adanilkina commented on docs/vacancy_drafts.md
> +cart_id | string | Идентификатор заказа
ааа ну ладно тогда

2021-05-21 06:38 UTC, user32338 commented on docs/vacancy_drafts.md
> +# Черновики вакансий
внимание вопрос, а никак нельзя достать еще и salary из черновика, а то у нас в дизайне он есть (ясно дело что он может быть не обязательным)

2021-05-21 08:42 UTC, AlexeyPuchko commented on docs/vacancy_autorenewal.md
> +```DELETE /vacancies/auto_renewal?vacancy_id=123456```
а тут не draft_id должен быть? с юай  стороны мы должны отменять автопубликацию с экрана черновиков, т.е. у нас есть только draft_id

2021-05-21 08:49 UTC, AlexeyPuchko commented on docs/vacancy_drafts.md
> +      "name": "Заведующий отделом розничных продаж",
кроме названия и локации(area) на UI еще отображается зарплата
```
    "salary": {
        "to": null,
        "from": 30000,
        "currency": "RUR",
        "gross": true
    }
```
@user32338 Антон, поправь меня, если что-то поменялось

2021-05-21 13:06 UTC, Afftobus commented on docs/vacancy_autorenewal.md
> +```DELETE /vacancies/auto_renewal?vacancy_id=123456```
В портфеле написано, что нужно уметь отменять автоматическое обновление, а оно к черновикам не очень имеет отношения. Эта фишка чисто про вакансию.

2021-05-21 13:06 UTC, Afftobus commented on docs/vacancy_drafts.md
> +      "name": "Заведующий отделом розничных продаж",
з/п добавлю.

2021-06-04 11:29 UTC, colorbash commented on docs/vacancy_drafts.md
> +* `403 Forbidden` — текущий пользователь не является работодателем
договорились выпустить когда добавим тут 404

2021-07-26 09:27 UTC, closed without merging