Add role catalog article
hhru/api pull request #535
Opened 2021-11-29 13:59 UTC by yyakhontov

2021-11-29 18:39 UTC, colorbash commented on docs/role_catalog_article.md
> +1. [Поиск резюме](https://github.com/hhru/api/blob/master/docs/resumes_search.md) - добавлен параметр 'professional_role' (при использовании параметра 'specialization' та же работает режим обратно со
та же

2021-11-29 18:39 UTC, colorbash commented on docs/role_catalog_article.md
> +2. [Поиск по вакансиям](https://github.com/hhru/api/blob/master/docs/vacancies.md#search) - добавлен параметр 'professional_role' (при использовании параметра 'specialization' та же работает режим об
та же

2021-11-29 18:39 UTC, colorbash commented on docs/role_catalog_article.md
> +
не хватает кондишенсов для резюме

2021-11-29 18:39 UTC, colorbash commented on docs/role_catalog_article.md
> +## Подробнее о поддержке нового каталога в API:
Субьективно не нравится слово Подробнее в заголовке, кажется `Поддержка нового каталога в API` и `Обратная совместимость нового каталога в API` норм

2021-11-29 18:39 UTC, colorbash commented on docs/role_catalog_article.md
> +Например, при использовании метода публикации вакансий, достаточно передать все значение из устаревшего справочника специализации, после публикации (с небольшим временным лагом) в данной вакансии буд
нового каталога специализаций (proff_roles)

2021-11-30 09:57 UTC, iriss22 requested changes

2021-11-30 09:57 UTC, iriss22 commented on docs/role_catalog_article.md
> +##### ВАЖНО: На время, пока производители интегрированных систем не поддержат новый каталог, в интегрированной системе клиенты могут использовать и "старый" каталог специализаций при публикации, наш
оБ обратной

2021-11-30 09:57 UTC, iriss22 commented on docs/role_catalog_article.md
> +##### ВАЖНО: На время, пока производители интегрированных систем не поддержат новый каталог, в интегрированной системе клиенты могут использовать и "старый" каталог специализаций при публикации, наш
а почему именно при публикации? Может просто написать, что некоторое время будет работать и старый и новый каталог?

2021-11-30 09:57 UTC, iriss22 commented on docs/role_catalog_article.md
> +Новый каталог специализаций (профессиональных ролей) - 'professional_roles'. Профессиональные роли приходят на замену [специализациям](https://github.com/hhru/api/blob/master/docs/specializations.md)
ты же говорил, что официально они продолжают называться специализациями. Мы тут не вносим путаницу?

2021-11-30 09:57 UTC, iriss22 commented on docs/role_catalog_article.md
> +Новый каталог специализаций (профессиональных ролей) - 'professional_roles'. Профессиональные роли приходят на замену [специализациям](https://github.com/hhru/api/blob/master/docs/specializations.md)
какой-то вообще не понятный абзац. Кажется этот и следующий надо объединить...
Как-то так:
Для нового каталога специализаций (профессиональных ролей) создан отдельный [справочник](https://api.hh.ru/openapi/redoc#tag/Spravochniki/paths/~1professional_roles/get) и [подсказки (autosuggest, autocomplete)](https://api.hh.ru/openapi/redoc#tag/Spravochniki/paths/~1suggests~1professional_roles/get) 
В настоящее время новый каталог специализаций (профессиональных ролей) и [устаревший каталог специализации](https://github.com/hhru/api/blob/master/docs/specializations.md) используются параллельно для обеспечения обратной совместимости.

2021-11-30 09:57 UTC, iriss22 commented on docs/role_catalog_article.md
> +Данное поле представлено в параметрах всех ключевых методах для работы с соответствующими сущностями (вакансии, резюме)
что значит ключевых?

2021-11-30 09:57 UTC, iriss22 commented on docs/role_catalog_article.md
> +Данное поле представлено в параметрах всех ключевых методах для работы с соответствующими сущностями (вакансии, резюме)
я бы удалила предложение

2021-11-30 09:57 UTC, iriss22 commented on docs/role_catalog_article.md
> +2. [Условия заполнения полей при добавлении и редактировании вакансий](https://github.com/hhru/api/blob/master/docs/employer_vacancies.md#%D1%83%D1%81%D0%BB%D0%BE%D0%B2%D0%B8%D1%8F-%D0%B7%D0%B0%D0%BF
Что значит предложение: "Подробнее о обратной совместимости". ? Ссылки не хватает?

2021-11-30 09:57 UTC, iriss22 commented on docs/role_catalog_article.md
> +1. [Поиск резюме](https://github.com/hhru/api/blob/master/docs/resumes_search.md) - добавлен параметр 'professional_role' (при использовании параметра 'specialization' та же работает режим обратно со
не понятно предложение в скобках

2021-11-30 09:57 UTC, iriss22 commented on docs/role_catalog_article.md
> +Процесс выбора специализации из нового каталога происходит автоматически после публикации вакансии/резюме (ранее опубликованные вакансии так же автоматически получили значения из нового каталога, они
после прочтения этого раздела кажется, что все хорошо и ничего дорабатывать не надо и так все автоматом выбарется

2021-11-30 09:57 UTC, iriss22 commented on docs/role_catalog_article.md
> +## Подробнее о обратной совместимости нового каталога в API:
оБ

2021-11-30 14:28 UTC, yyakhontov commented on docs/role_catalog_article.md
> +##### ВАЖНО: На время, пока производители интегрированных систем не поддержат новый каталог, в интегрированной системе клиенты могут использовать и "старый" каталог специализаций при публикации, наш
Ну это фокус на тех, кого мы боимся :)

2021-11-30 14:38 UTC, yyakhontov commented on docs/role_catalog_article.md
> +Новый каталог специализаций (профессиональных ролей) - 'professional_roles'. Профессиональные роли приходят на замену [специализациям](https://github.com/hhru/api/blob/master/docs/specializations.md)
Не понимаю, что в этом непонятного :) Просым языком о том, что изменилось же, не?

2021-12-01 08:39 UTC, iriss22 commented on docs/role_catalog_article.md
> +Новый каталог специализаций (профессиональных ролей) - 'professional_roles'. Профессиональные роли приходят на замену [специализациям](https://github.com/hhru/api/blob/master/docs/specializations.md)
мне кажется, что так как я написала понятнее. Но решать тебе

2021-12-01 10:50 UTC, iriss22 approved these changes
минорные замечания

2021-12-01 10:50 UTC, iriss22 commented on docs/role_catalog_article.md
> +Все ранее опубликованные вакансии, автоматически получили значения из нового каталога профессиональных ролей, дополнительно изменять эти вакансии не требуется.
первая запятая лишняя

2021-12-01 10:50 UTC, iriss22 commented on docs/role_catalog_article.md
> +Новый каталог специализаций (профессиональных ролей) - 'professional_roles'. Новый каталог специализаций (профессиональных ролей) приходит на замену [специализациям](https://github.com/hhru/api/blob/
кажется первое предложение лишнее

2021-12-01 10:50 UTC, iriss22 commented on docs/role_catalog_article.md
> +3. [Публикация резюме](https://github.com/hhru/api/blob/master/docs/resumes.md#%D0%BF%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F-%D1%80%D0%B5%D0%B7%D1%8E%D0%BC%D0%B5) - - добавлен параметр
лишнее тире

2021-12-02 11:57 UTC, merged