minor fixes\adding error description
hhru/api pull request #547
Opened 2022-02-16 13:06 UTC by DanilKnyazev

2022-02-16 14:03 UTC, mvxio commented on docs/errors.md
> +| 403       | oauth | user_auth_expected    | выполняется запрос с авторизацией приложения, для выполнения которого необходима [авторизация пользователя](authorization_for_user.md) |
Чет я не уверен, что такое выравнивание удобнее, чем было

2022-02-16 14:04 UTC, mvxio commented on docs/vacancies.md
> +403 | captcha_required | captcha_required | [Подробнее о капче](errors.md#%D0%BD%D0%B5%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C-%D0%BF%D1%80%D0%BE%D0%B9%D1%82%D0%B8-%D0%BA%D0
Точно нужен escaped url?

2022-02-16 14:05 UTC, mvxio commented on docs/vacancy_drafts.md
> +Активная автопубликация означает что при поступлении оплаты по счету, номер которого указан в объекте, произойдёт
👍

2022-02-16 14:05 UTC, mvxio requested changes
пара вопросов

2022-02-16 16:30 UTC, mvxio approved these changes

2022-02-21 14:37 UTC, adanilkina commented on docs/employer_vacancies.md
> +| archived_at                        | строка   | дата архивации вакансии                       |
верни пожалуйста форматирование, как было до

уже был как-то раз разговор про это и мы решили оставить старое форматирование

2022-02-22 11:12 UTC, mvxio approved these changes

2022-02-24 08:40 UTC, merged