уточнения для professional_roles
hhru/api pull request #578
Opened 2022-04-22 14:50 UTC by DanilKnyazev

2022-04-25 14:57 UTC, bokshitsky commented on docs/employer_vacancies.md
> +professional_roles | array | массив профессиональных ролей с количеством элементов равным 1 [при использовании параметра](#with_professional_roles) `with_professional_roles=true`
там выше на английском - array

2022-04-25 16:33 UTC, DanilKnyazev commented on docs/employer_vacancies.md
> +professional_roles | array | массив профессиональных ролей с количеством элементов равным 1 [при использовании параметра](#with_professional_roles) `with_professional_roles=true`
> там выше на английском - array

т.е. нужно массив изменить на список?

2022-04-26 09:58 UTC, adanilkina requested changes

2022-04-26 09:58 UTC, adanilkina commented on docs/employer_vacancies.md
> +professional_roles | array | массив профессиональных ролей с количеством элементов равным 1 [при использовании параметра](#creation-with_professional_roles) `with_professional_roles=true`
зачем уточнять, что там 1 элемент? 
еси их станет больше, то дока перестанет быть актуальной

2022-04-26 09:58 UTC, adanilkina commented on docs/employer_vacancies.md
> +Без этого параметра массив `professional_roles` необязателен и игнорируется
не оч поняла зачем править на массив, если возвращается **поле** professional_roles, а ниже указан тип этого поля.
мы нигде не пишем, что за тип возвращается по конкретному полю - для этого есть таблица ниже, например specializations это тоже массив, но мы не ишем о типе этого поля

2022-04-27 14:27 UTC, adanilkina approved these changes

2022-04-27 14:44 UTC, closed without merging