OpenAPI links & contents
hhru/api pull request #581
Opened 2022-05-06 12:47 UTC by DanilKnyazev

2022-05-06 13:07 UTC, Diacrome requested changes
жду доработок

2022-05-11 07:17 UTC, Diacrome approved these changes

2022-05-18 11:51 UTC, Diacrome requested changes
см замечания

2022-05-18 11:51 UTC, Diacrome commented on docs/languages.md
> -# Справочник языков
ты удаляшеь файл но на него еще есть ссылки 
https://github.com/hhru/api/search?q=languages.md
например в [docs/resumes_search.md](https://github.com/hhru/api/blob/cc4de2f0291f51261934ec5052173e1e11370146/docs/resumes_search.md)

2022-05-18 11:51 UTC, Diacrome commented on docs_eng/languages.md
> -# Language directory
ты удаляшеь файл но на него еще есть ссылки
https://github.com/hhru/api/search?q=languages.md
например в docs_eng/resumes_search.md

2022-05-18 12:12 UTC, DanilKnyazev commented on docs/languages.md
> -# Справочник языков
исправил

2022-05-18 12:12 UTC, DanilKnyazev commented on docs_eng/languages.md
> -# Language directory
исправил

2022-05-18 12:19 UTC, Diacrome approved these changes

2022-05-19 07:58 UTC, closed without merging