Добавить описание поля language для вакансий
hhru/api pull request #585
Opened 2022-05-17 14:37 UTC by a-busarov

2022-05-17 14:39 UTC, colorbash commented on docs/vacancies.md
> +languages | array | Список языков. Элементы справочника [languages](languages.md).
не оч понятно список языков чего?
это требования к кандидату в вакансии?

2022-05-19 14:49 UTC, adanilkina commented on docs/vacancies.md
> +languages | array | Список языков. Элементы справочника [languages](languages.md).
да типа в вакансии можно указать ззнание языков, как в резюме и мы добавляем их в  вакансию

тип: 
array или null - на самом деле поле отсутсвует, если не заполнено в вакансии

2022-05-20 08:28 UTC, adanilkina requested changes
поправь пожалуйста обязательность поля

2022-05-30 07:42 UTC, colorbash approved these changes

2022-05-31 08:01 UTC, a-busarov commented on docs/vacancies.md
> +languages | array | Список языков. Элементы справочника [languages](languages.md).
Поправил на Список языков, которыми должен владеть кандидат

2022-05-31 09:20 UTC, merged