Добавлен новый тип ошибки - not_available_area
hhru/api pull request #613
Opened 2022-08-01 15:38 UTC by sabkaryan

2022-08-01 17:06 UTC, colorbash requested changes

2022-08-01 18:38 UTC, sabkaryan commented on docs/resumes.md
> +not_available_area | недопустимое значение региона
У зарплаты нельзя указать не русский регион при создании резюме
Но у зарплаты нет своей соискательской доки, поэтому добавляем ошибку в общую доку

2022-08-01 18:43 UTC, sabkaryan commented on docs/resumes.md
> +not_available_area | недопустимое значение региона
Хотели в описании ошибки написать, что валидны только русские регионы. Если сделать общую ошибку not_available, то так уже не получится сделать

2022-08-02 11:18 UTC, colorbash approved these changes

2022-08-09 10:34 UTC, merged