добавлено описание параметра changed_after для адресов работодателя
hhru/api pull request #614
Opened 2022-08-04 09:49 UTC by it3r

2022-08-04 13:28 UTC, iriss22 requested changes

2022-08-04 13:28 UTC, iriss22 commented on docs/employer_addresses.md
> +* `changed_after` – дата, которая ограничивает снизу дату добавления, удаления или последнего изменения адреса.
думаю стоит написать, что в этом случае не работает пагинация

2022-08-04 13:28 UTC, iriss22 commented on docs/employer_addresses.md
> +* `changed_after` – дата, которая ограничивает снизу дату добавления, удаления или последнего изменения адреса.
я бы написала так: позволяет загрузить все изменения (добавление, удаление или изменение адреса) по адресам, начиная с этой даты

2022-08-04 13:29 UTC, it3r commented on docs/employer_addresses.md
> +* `changed_after` – дата, которая ограничивает снизу дату добавления, удаления или последнего изменения адреса.
ок

2022-08-04 13:34 UTC, it3r commented on docs/employer_addresses.md
> +* `changed_after` – дата, которая ограничивает снизу дату добавления, удаления или последнего изменения адреса.
так попонятней и вправду)

2022-08-04 13:39 UTC, iriss22 approved these changes

2022-08-04 13:39 UTC, iriss22 commented on docs/employer_addresses.md
> +* `changed_after` – позволяет загрузить все изменения (добавление, удаление или изменение адреса) по адресам, начиная с этой даты.
там вроде кстати, > 
те после этой даты

2022-08-04 13:45 UTC, iriss22 approved these changes

2022-08-04 13:53 UTC, adanilkina reviewed
в документации нет описания новых ошибок, которые мы будем выдавать
как минимум повился новый тип changed_after

2022-08-05 15:28 UTC, adanilkina commented on docs/employer_addresses.md
> +* `400 Bad Request` – ошибка в параметре запроса `changed_after`
а 400 возвращается только в этом случае? 
еси да тонаверн пока норм, вобще обычно как раз выносим ошибки в errors.md, но из-за 1 не стоит, мб кода появятся др методы поправить

2022-08-08 09:40 UTC, it3r commented on docs/employer_addresses.md
> +* `400 Bad Request` – ошибка в параметре запроса `changed_after`
могут ещё быть ошибки с параметрами с номерами страниц

2022-08-08 09:57 UTC, adanilkina approved these changes

2022-08-11 13:48 UTC, closed without merging