Перенесли возможные варианты публикации вакансий у текущего менеджера в OpenAPI
hhru/api pull request #647
Opened 2022-10-19 14:09 UTC by DaniilIdrisov

2022-10-21 12:03 UTC, alena-nikiforova-hh requested changes

2022-10-21 12:37 UTC, DaniilIdrisov commented on docs/employer_vacancies.md
>  ## Возможные варианты публикации вакансий у текущего менеджера
В опенапи уже релизнулась задача. Могу создать задачу на изменение в опен апи и исправить, если нужно

2022-10-21 12:37 UTC, DaniilIdrisov commented on docs/employer_vacancies.md
>  ## Возможные варианты публикации вакансий у текущего менеджера
@alena-nikiforova-hh  Сделать?

2022-10-21 13:41 UTC, DaniilIdrisov commented on docs/employer_vacancies.md
>  ## Возможные варианты публикации вакансий у текущего менеджера
@adanilkina Посмотри пожалуйста какой вариант лучше сделать?

2022-10-26 07:43 UTC, adanilkina commented on docs/employer_vacancies.md
>  ## Возможные варианты публикации вакансий у текущего менеджера
да вобще не принципиально кмк, отдельную задачу не надо, еси решишь поправить лучше в текущей какой-ниб на доку поправь

2022-10-26 07:44 UTC, alena-nikiforova-hh approved these changes

2022-11-18 14:47 UTC, closed without merging