Добавлено описание для просмотров вакансии
hhru/api pull request #657
Opened 2022-11-01 11:23 UTC by sabkaryan

Добавлено описание возможности просмотра посетителей вакансии

2022-11-01 14:39 UTC, DanilKnyazev requested changes

2022-11-01 14:39 UTC, DanilKnyazev commented on docs/employer_vacancies.md
> +то вернется самое свежее
непонятно, что подразумевается по свежим резюме: созданное последний резюме, опубликованное последним резюме или отредактированное последним резюме из списка?

2022-11-02 09:09 UTC, DanilKnyazev approved these changes

2022-11-02 17:52 UTC, user32338 approved these changes

2022-11-18 14:46 UTC, closed without merging