Add target employer count example to vacancies.md
hhru/api pull request #660
Opened 2022-11-09 13:09 UTC by yaeuge

2022-11-09 13:41 UTC, colorbash requested changes

2022-11-09 13:41 UTC, colorbash commented on docs/vacancies.md
> +        "applicant_services": {
надо внизу в таблицу добавить описание

2022-11-09 13:52 UTC, yaeuge commented on docs/vacancies.md
> +        "applicant_services": {
там внизу ссылка на документацию эмплоера в openapi, в которой это поле описано (здесь https://github.com/hhru/hhapi/pull/2287)

2022-11-15 12:51 UTC, colorbash approved these changes

2022-11-21 09:39 UTC, merged