Добавлен параметр для поиска по ФИО кандидата в откликах конкретной в…
hhru/api pull request #720
Opened 2023-04-03 17:47 UTC by Smolov-Denis

https://github.com/hhru/api/blob/master/docs/resumes_search.md

2023-04-04 11:26 UTC, colorbash requested changes

2023-04-04 11:26 UTC, colorbash commented on docs/resumes_search.md
> +* `search_by_vacancy_id` — идентификатор резюме. Поиск будет происходить в откликах на данное резюме.
search_by_vacancy_id и vacancy_id ну очень похожи..
может завязаться на флаг search_in_responses?
если он пришел то искать не среди подходящих(vacancy_id), а среди откликов?

2023-04-04 16:43 UTC, Smolov-Denis commented on docs/resumes_search.md
> +* `search_by_vacancy_id` — идентификатор резюме. Поиск будет происходить в откликах на данное резюме.
![Screenshot from 2023-04-04 19-41-18](https://user-images.githubusercontent.com/96125694/229860317-181c4c5d-108a-4458-a05f-16864ec1a4e0.png)

2023-04-04 16:43 UTC, Smolov-Denis commented on docs/resumes_search.md
> +* `search_by_vacancy_id` — идентификатор резюме. Поиск будет происходить в откликах на данное резюме.
![Screenshot from 2023-04-04 19-41-29](https://user-images.githubusercontent.com/96125694/229860338-1a8661a4-c9ad-422d-96be-c4e0166c08df.png)

2023-04-04 16:45 UTC, Smolov-Denis commented on docs/resumes_search.md
> +* `search_by_vacancy_id` — идентификатор резюме. Поиск будет происходить в откликах на данное резюме.
search-team аппрувнула оба PR по лоджику и resume-search

2023-04-05 05:49 UTC, iapasternak approved these changes

2023-04-05 06:42 UTC, DanilKnyazev commented on docs/resumes_search.md
> +* `search_by_vacancy_id` — идентификатор резюме. Поиск будет происходить в откликах на данное резюме.
идентификатор резюме? а параметр search_by_**vacancy_id** как будто бы про вакансию говорит.

2023-04-05 06:45 UTC, iapasternak approved these changes

2023-04-05 06:46 UTC, Smolov-Denis commented on docs/resumes_search.md
> +* `search_by_vacancy_id` — идентификатор резюме. Поиск будет происходить в откликах на данное резюме.
Вот это я, конечно, пропарился. Спасибо за бдительность!

2023-04-05 07:20 UTC, DanilKnyazev commented on docs_eng/resumes_search.md
> +* `search_in_responses` — `true`: search only in resumes with which applicants responded to vacancies of the current user's company,
кажется такой вариант норм:
search is only in resumes with applicants who responded to vacancies of the current user's company

2023-04-05 07:24 UTC, DanilKnyazev approved these changes

2023-04-05 07:25 UTC, Smolov-Denis commented on docs_eng/resumes_search.md
> +* `search_in_responses` — `true`: search only in resumes with which applicants responded to vacancies of the current user's company,
Заменил на твой вариант, только глагол is меня смутил. Тут search - это "ищем", "искать", а не "поиск".

2023-04-24 06:43 UTC, merged