WIP: Добавлены параметры для поиска по откликам
hhru/api pull request #726
Opened 2023-04-24 13:26 UTC by Smolov-Denis

Добавлены параметры для поиска по откликам.

2023-04-24 13:59 UTC, Diacrome reviewed
в англ. боку было бы неплохо жобавить

2023-04-24 14:08 UTC, colorbash approved these changes

2023-04-24 14:08 UTC, colorbash commented on docs/employer_negotiations.md
> +university | нет | Название учебного заведения
тут точно не ид?

2023-04-24 14:18 UTC, Smolov-Denis commented on docs/employer_negotiations.md
> +university | нет | Название учебного заведения
Заменил на ID.

2023-04-24 14:38 UTC, DanilKnyazev requested changes

2023-04-24 14:38 UTC, DanilKnyazev commented on docs/employer_negotiations.md
> +citizenship | нет | Страна желаемого гражданства. Возможные значения можно посмотреть в справочнике стран
тут бы ссылку на этот справочник стран

2023-04-24 14:38 UTC, DanilKnyazev commented on docs/employer_negotiations.md
> +language | нет | Знание языков. Можно указать несколько значений. Задается в формате language.level, где: `language` — значение из справочника [/languages](https://api.hh.ru/openapi/redoc#tag/Obshie-
language.level=A2&language.level= 
несколько параметров как указываются через апмер санд или запятую?

2023-04-24 14:38 UTC, DanilKnyazev commented on docs/employer_negotiations.md
> +show_only_new_responses | нет | Показывать только новые отклики
что значит новые? непрочитанные?

2023-04-24 14:38 UTC, DanilKnyazev commented on docs/employer_negotiations.md
> +university | нет | Идентификатор учебного заведения
а где значения взять?

2023-04-24 14:44 UTC, Smolov-Denis commented on docs/employer_negotiations.md
> +citizenship | нет | Страна желаемого гражданства. Возможные значения можно посмотреть в справочнике стран
Добавил.

2023-04-24 14:46 UTC, Smolov-Denis commented on docs/employer_negotiations.md
> +language | нет | Знание языков. Можно указать несколько значений. Задается в формате language.level, где: `language` — значение из справочника [/languages](https://api.hh.ru/openapi/redoc#tag/Obshie-
Добавил.

2023-04-24 14:46 UTC, Smolov-Denis commented on docs/employer_negotiations.md
> +show_only_new_responses | нет | Показывать только новые отклики
Да.

2023-04-24 14:50 UTC, Smolov-Denis commented on docs/employer_negotiations.md
> +university | нет | Идентификатор учебного заведения
Добавил.

2023-04-24 14:59 UTC, DanilKnyazev requested changes

2023-04-24 14:59 UTC, DanilKnyazev commented on docs/employer_negotiations.md
> +show_only_new_responses | нет | Показывать только новые отклики
тут тоже надо добавить пару слов для уточнения. Будут вопросы, если этого не сделать. Особенно у тех, кто впервые доку открыл.

2023-04-24 15:06 UTC, colorbash commented on docs/employer_negotiations.md
> +university | нет | Идентификатор [учебного заведения](https://github.com/hhru/api/blob/master/docs_eng/suggests.md)
если тут ид то чего не university_id?

2023-04-24 16:51 UTC, Smolov-Denis commented on docs/employer_negotiations.md
> +show_only_new_responses | нет | Показывать только новые отклики
Ok

2023-04-25 06:15 UTC, DanilKnyazev approved these changes

2023-05-04 07:54 UTC, closed without merging